# Generated by Django 3.2.13 on 2022-04-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='isStudent',
            field=models.BooleanField(default=False),
        ),
    ]
