# Generated by Django 3.2.13 on 2022-04-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20220419_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=10)),
            ],
        ),
    ]
