# Generated by Django 3.2.13 on 2022-04-20 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperAdmin', '0005_quiz_createdby'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='post',
            field=models.BooleanField(default=False),
        ),
    ]
